# fly.toml app configuration file generated for djforge-client on 2025-07-13T18:19:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'djforge-client'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    VITE_API_URL = 'https://djforge-server.fly.dev'

[env]
  NODE_ENV = 'production'

# Modern Fly.io configuration for HTTP service
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 10
    soft_limit = 5

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
