# fly.toml app configuration file generated for djforge-server on 2025-07-13T18:18:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'djforge-server'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'
  LOG_RETENTION_DAYS = '90'

# Modern Fly.io configuration for HTTP service with WebSocket support
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/health'

  # WebSocket health check
  [[http_service.checks]]
    interval = '60s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/websocket/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    port = 8080

# Machine restart policy
[[restart]]
  policy = "on-failure"
  max_retries = 3
